version: "3.7"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
    volumes:
      - postgres:/var/lib/postgresql/data
  app:
    build: .
    restart: always
    ports:
      - "80:3000"
    depends_on:
      - db
networks:
  default:
    name: workspace-net
volumes:
  postgres: