default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['DEVELOPMENT_DB_NAME'] %>
  user: <%= ENV['DEVELOPMENT_DB_USER'] %>
  password: <%= ENV['DEVELOPMENT_DB_PASSWORD'] %>
  port: <%= ENV['DEVELOPMENT_DB_PORT'] %>

test:
  <<: *default
  database: <%= ENV['TEST_DB_NAME'] %>
  user: <%= ENV['TEST_DB_USER'] %>
  password: <%= ENV['TEST_DB_PASSWORD'] %>
  port: <%= ENV['TEST_DB_PORT'] %>

production:
  <<: *default
  database: <%= ENV['PRODUCTION_DB_NAME'] %>
  user: <%= ENV['PRODUCTION_DB_USER'] %>
  password: <%= ENV['PRODUCTION_DB_PASSWORD'] %>
  port: <%= ENV['PRODUCTION_DB_PORT'] %>
